# Generated by Django 5.0.1 on 2024-01-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Сколько раз использовался')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('products', models.ManyToManyField(related_name='ProductRecipe', to='cook_book.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20, verbose_name='Вес продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_book.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_book.recipe')),
            ],
        ),
    ]
