# Generated by Django 5.0.1 on 2024-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecipe',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес продукта'),
        ),
    ]
