# Generated by Django 5.0.1 on 2024-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название рецепта'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecipe',
            unique_together={('product', 'recipe')},
        ),
    ]
